Repository ray-di/ray-di.github.io, pull requests merged in 2022-02, with the labels that each got.

#2 Import changes
  manuals/1.0/en/MentalModel.md
  manuals/1.0/en/Motivation.md
Labels: en

#8 Add Japenese menu
  _includes/manuals/1.0/ja/contents.html
Labels: ja

#3 Update injections
  manuals/1.0/en/Injections.md
Labels: en

#14 Translate Scopes
  manuals/1.0/ja/Scopes.md
Labels: ja

#11 Translate Installation
  manuals/1.0/ja/Installation.md
Labels: ja

#10 Translate Overview
  manuals/1.0/ja/Overview.md
Labels: ja

#12 Translate Getting Started
  manuals/1.0/en/GettingStarted.md
  manuals/1.0/ja/GettingStarted.md
Labels: ja

#18 Add performance boost page
  _includes/manuals/1.0/en/contents.html
  _includes/manuals/1.0/ja/contents.html
  manuals/1.0/en/PerformanceBoost.md
  manuals/1.0/ja/PerformanceBoost.md
Labels: en, ja

#9 Translate Motivation
  manuals/1.0/ja/Motivation.md
Labels: ja

#15 Translate Mental Model
  manuals/1.0/en/MentalModel.md
  manuals/1.0/ja/MentalModel.md
Labels: ja

#24 Import best practice pages from Guice Wiki
  manuals/1.0/en/BestPractices.md
  manuals/1.0/en/bp/AvoidConditionalLogicInModules.md
  manuals/1.0/en/bp/AvoidStaticState.md
  manuals/1.0/en/bp/CyclicDependencies.md
  manuals/1.0/en/bp/DocumentPublicBindings.md
  manuals/1.0/en/bp/DontReuseAnnotations.md
  manuals/1.0/en/bp/InjectOnlyDirectDependencies.md
  manuals/1.0/en/bp/InjectingTheInjector.md
  manuals/1.0/en/bp/KeepConstructorsHidden.md
  manuals/1.0/en/bp/MinimizeMutability.md
  manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
  manuals/1.0/en/bp/OrganizeModulesByFeature.md
Labels: en

#26 translate Injections.md to ja
  manuals/1.0/ja/Injections.md
Labels: ja

#41 Update title of OrganizeModulesByFeature
  manuals/1.0/en/bp/OrganizeModulesByFeature.md
Labels: en

#27 improve description of Setter Injection in Injections.md
  manuals/1.0/en/Injections.md
Labels: en

#31 Change for Ray.Di: AvoidConditionalLogicInModules
  manuals/1.0/en/bp/AvoidConditionalLogicInModules.md
Labels: en

#37 Change for Ray.Di: Avoid static state
  manuals/1.0/en/bp/AvoidStaticState.md
Labels: en

#32 Change for Ray.Di: Minimize mutability
  manuals/1.0/en/bp/MinimizeMutability.md
Labels: en, best practise

#33 Change for Ray.Di: InjectOnlyDirectDependencies
  manuals/1.0/en/bp/InjectOnlyDirectDependencies.md
Labels: en, best practise

#39 Remove KeepConstructorsHidden
  manuals/1.0/en/bp/KeepConstructorsHidden.md
Labels: en

#42 Change for Ray.Di: Document public bindings
  manuals/1.0/en/bp/DocumentPublicBindings.md
Labels: en, best practise

#34 Change for Ray.Di: InjectingTheInjector
  manuals/1.0/en/bp/InjectingTheInjector.md
Labels: en, best practise
