Repository ray-di/ray-di.github.io, pull requests merged in 2022-03, with the labels that each got.

#43 Translate InstanceBindings.md to ja
  manuals/1.0/ja/InstanceBindings.md
Labels: en

#38 Change for Ray.Di: ModulesShouldBeFastAndSideEffectFree
  manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
Labels: en, best practise

#35 Translated the section "Constructor Bindings" from En to Ja
  manuals/1.0/ja/ConstructorBindings.md
Labels: ja

#44 Translate ProviderBindings.md to Japanese
  manuals/1.0/ja/ProviderBindings.md
Labels: ja

#53 Translate Built in bindings into Ja
  manuals/1.0/en/BuiltinBindings.md
  manuals/1.0/ja/BuiltinBindings.md
Labels: ja

#55 Translate Object Life cycle into Ja
  manuals/1.0/ja/ObjectLifeCycle.md
Labels: ja

#47 Add Multi bindings
  _includes/manuals/1.0/en/contents.html
  _includes/manuals/1.0/ja/contents.html
  manuals/1.0/en/Multibindings.md
  manuals/1.0/ja/Multibindings.md
Labels: en, ja

#48 Translate "Graphing Applications" into Japanese
  manuals/1.0/en/Grapher.md
  manuals/1.0/ja/Grapher.md
Labels: ja

#50 Translate Untargeted bindings into Ja
  manuals/1.0/en/UntargetedBindings.md
  manuals/1.0/ja/UntargetedBindings.md
Labels: ja

#49 Translate Binding Attributes into Ja
  manuals/1.0/en/BindingAttributes.md
  manuals/1.0/ja/BindingAttributes.md
Labels: ja
